version: '3.8'
services:
  pg:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    container_name: pg
  cloudbeaver:
    container_name: dbeaver
    image: dbeaver/cloudbeaver:23.2
    restart: unless-stopped
    ports:
      - "8978:8978"
  migrations:
    image: migrations:latest
    container_name: migrations
    environment:
      DEFAULT_DB_URL: host=pg user=postgres password=postgres dbname=postgres port=5432 sslmode=disable TimeZone=Asia/Shanghai
      DB_URL: host=pg user=postgres password=postgres dbname=ams port=5432 sslmode=disable TimeZone=Asia/Shanghai
      DB_NAME: ams
    depends_on:
      - pg
  api:
    image: api:latest
    container_name: api
    ports:
      - '8080:8080'
    environment:
      DEFAULT_DB_URL: host=pg user=postgres password=postgres dbname=postgres port=5432 sslmode=disable TimeZone=Asia/Shanghai
      DB_URL: host=pg user=postgres password=postgres dbname=ams port=5432 sslmode=disable TimeZone=Asia/Shanghai
      DB_NAME: ams
    depends_on:
      - migrations
  app:
    image: app:latest
    container_name: app
    ports:
      - '3000:3000'
    environment:
      NEXT_PUBLIC_WS_URL: ws://localhost:8070
      NEXT_PUBLIC_API_URL: http://localhost:8080
      NEXT_PUBLIC_WEIGHT_MANUAL: 'true'
    depends_on:
      - api
  static:
    image: static:latest
    container_name: static
    ports:
      - '4000:80'
  # ws:
  #   image: ws:latest
  #   container_name: ws
  #   ports:
  #     - '8070:8070'